### ISSUE TITLE
Where can i get validated samples?

### ISSUE THREAD

**Issue by a00101** [hyunhwaj/CB2-Experiments#1]
Thanks for useful data.
I don't get website at broad TNF dataset because not found error.
Where can i get TNF high low dataset or can i get through GEO or EBI ?

Thank you.

**Comment by hyunhwan-jeong** [comment]
Hi @a00101, I don't think they have deposited their data to any public database. So, It is not possible to get the TNF dataset if the website is off. I guess the website has been removed since the corresponding author has moved outside of Broad Institute. What type of data are you looking for? Do you want to find FASTQs?

Hyun-Hwan Jeong

**Comment by a00101** [comment]
Thank you for your rapid and considerate response.
right. I want fastqs labelled TNF-low and high or GFP and presort.

**Comment by hyunhwan-jeong** [comment]
I would recommend to contact the authors, 

Best,

Hyun-Hwan Jeong
